version: '3.9'
services:
  process:
    build: .
    hostname: process
    container_name: aps_process
    networks:
     - aps-network    
    environment:
     JAVA_OPTS: " -Xms256m -Xmx1g"
    ports:
    - 8080:8080
    depends_on:
      - postgres
      - elasticsearch
      - process-admin
    volumes:
      - aps-contentstore-sa-volume:/act_data

  process-admin:
    build:
      context: .
      dockerfile: Dockerfile-admin
    hostname: process-admin
    container_name: aps_process_admin
    networks:
     - aps-network  
    environment:
      JAVA_OPTS: " -Xms256m -Xmx512m"
    ports:
    - 9090:9090
    depends_on:
      - postgres-admin

  elasticsearch:
    hostname: elasticsearch
    container_name: aps_elasticsearch
    networks:
     - aps-network  
    image: elasticsearch:7.13.2
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: -Xms512m -Xmx512m
    ports:
      - 9300:9300
      - 9200:9200
    volumes:
      - aps-es-sa-volume:/usr/share/elasticsearch/data

  postgres:
    hostname: postgres
    container_name: aps_postgres
    networks:
     - aps-network  
    image: postgres:13.1
    environment:
      POSTGRES_DB: activiti
      POSTGRES_USER: alfresco
      POSTGRES_PASSWORD: alfresco
    ports:
      - 5432:5432
    volumes:
      - aps-db-sa-volume:/var/lib/postgresql/data

  postgres-admin:
     hostname: postgres-admin
     container_name: aps_postgres_admin
     networks:
     - aps-network  
     image: postgres:13.1
     environment:
       POSTGRES_DB: activiti-admin
       POSTGRES_USER: alfresco
       POSTGRES_PASSWORD: alfresco
     ports:
       - 5433:5433
     expose:
     - "5433"
     volumes:
       - aps-admin-db-sa-volume:/var/lib/postgresql/data
     command: -p 5433

networks:
    aps-network:
     name: aps-network

volumes:
    aps-db-sa-volume:
      external: true
    aps-admin-db-sa-volume:
      external: true
    aps-contentstore-sa-volume:
      external: true
    aps-es-sa-volume:
      external: true
